[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  base = "stable-branch"

# Environment variables needed for Edge Functions
[build.environment]
  VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}"
  VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"
  SUPABASE_URL = "${SUPABASE_URL}"
  SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"
  SUPABASE_SERVICE_KEY = "${SUPABASE_SERVICE_KEY}"
  SUPABASE_PROJECT_ID = "${SUPABASE_PROJECT_ID}"
  JWT_SECRET = "${JWT_SECRET}"
  ZOHO_SMTP_USERNAME = "${ZOHO_SMTP_USERNAME}"
  ZOHO_SMTP_PASSWORD = "${ZOHO_SMTP_PASSWORD}"

# Add CORS headers for Supabase Edge Functions
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization, x-client-info, apikey"
